DISCORD_TOKEN = "NzI2NTQ5ODQyNjk1ODE1MjMw.Xve6RQ.1eDTfkYNeVye3YU6MlBZ7CViWwI"
COMMAND_PREFIX = "-"
ACTIVITY1 = "-help"
ACTIVITY2 = "Use -help for help"
REDDIT_APP_ID="Zd09RzeD5RYSCw"
REDDIT_APP_SECRET= "LU3JXTyFdbxY7HOrsbmSsYPbY-Y"
REDDIT_SUBS= ['dankmemes','memes','ich_iel']
REDDIT_NSFW_SUBS = ['']
user_agent =  "Benni:%s:1.0 by u/Venti0r"